### PR TITLE
Fix generate model for sails version 1

### PR DESCRIPTION
**Pull request by 2012mjm**
Fix generate model for sails version 1

### CODE REVIEW

**Comment by juliandavidmr** [comment]
@2012mjm thank you very much

**Comment by 2012mjm** [comment]
Do you put the new version on npm?

**Comment by juliandavidmr** [comment]
@2012mjm  At this time I have no way to verify your changes, however, I will publish the package.

**Comment by juliandavidmr** [comment]
**Published:** https://www.npmjs.com/package/sails-inverse-model/v/2.0.7-0
**Version:** 2.0.7-0

**Pull request merged**
